#!/usr/bin/env python3
"""Build the OpenAI/Codex adapter from the canonical files, or check it.

The Codex plugin specification places skills at `skills/<skill-name>/SKILL.md`,
and Claude Code and the Skills CLI both read the repository-root `SKILL.md`.
One canonical set of files serves both: this script copies that set into
`adapters/codex/grounded-copy/` and writes the two files the adapter needs of
its own, and `--check` fails when the committed adapter drifts from the source.

Every copy is byte-for-byte, in binary mode, so a line-ending policy applied to
the source applies to the copy unchanged.

The adapter carries the skill, the pattern catalog, the linter, and the sample
corpora. The session hooks, the profiles, the slash command, the governing
directive, and the preference file are Claude Code features, and the adapter
ships none of them.

Usage:
    build_codex_adapter.py            write the adapter
    build_codex_adapter.py --check    compare, exit 1 on any difference
"""

import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ADAPTER = os.path.join("adapters", "codex", "grounded-copy")
SKILL_DIR = os.path.join(ADAPTER, "skills", "grounded-copy")

VERSION = "0.2.0"

EXIT_OK = 0
EXIT_DRIFT = 1

# (source, destination), both relative to the repository root.
COPIES = (
    ("SKILL.md", os.path.join(SKILL_DIR, "SKILL.md")),
    ("references/patterns.md", os.path.join(SKILL_DIR, "references", "patterns.md")),
    ("references/setup.md", os.path.join(SKILL_DIR, "references", "setup.md")),
    ("scripts/copy_lint.py", os.path.join(SKILL_DIR, "scripts", "copy_lint.py")),
    ("tests/bad-samples.md", os.path.join(SKILL_DIR, "tests", "bad-samples.md")),
    ("tests/good-samples.md", os.path.join(SKILL_DIR, "tests", "good-samples.md")),
    ("LICENSE", os.path.join(ADAPTER, "LICENSE")),
)

MANIFEST = """{
  "name": "grounded-copy",
  "version": "%s",
  "description": "Copy states what the subject is or does: concrete nouns, verbs, and specifics, checked by a zero-dependency Python linter. This adapter carries the skill, the pattern catalog, the linter, and the sample corpora. The session hooks, the three profiles, and the slash command are Claude Code features and are absent here.",
  "author": {
    "name": "HiroHyun",
    "url": "https://github.com/HiroHyun"
  },
  "homepage": "https://github.com/HiroHyun/grounded-copy",
  "repository": "https://github.com/HiroHyun/grounded-copy",
  "license": "MIT",
  "keywords": ["copywriting", "style", "linter", "i18n"],
  "skills": "./skills/"
}
""" % VERSION

README = """# grounded-copy — Codex adapter

Generated by `scripts/build_codex_adapter.py` in
https://github.com/HiroHyun/grounded-copy. Edit the canonical files there and
rebuild; `--check` fails when this tree drifts from them.

## What this adapter provides

- `skills/grounded-copy/SKILL.md` — the rules, byte-for-byte from the canonical
  skill.
- `skills/grounded-copy/references/patterns.md` — the pattern catalog, with a
  bad to good rewrite for every shape, and nine locales at three depths of
  regex coverage.
- `skills/grounded-copy/scripts/copy_lint.py` — the deterministic gate.
  Zero dependencies beyond Python 3. Exit 0 passes, 1 asks for a rewrite,
  2 reports a usage or IO error.
- `skills/grounded-copy/tests/` — the two sample corpora. `bad-samples.md` must
  fail the linter and `good-samples.md` must pass it.

Run the linter from the installed skill directory:

    python3 skills/grounded-copy/scripts/copy_lint.py draft.md locales/en.json
    cat draft.md | python3 skills/grounded-copy/scripts/copy_lint.py --stdin

## What this adapter leaves to Claude Code

The `SessionStart` policy, the `UserPromptSubmit` turn reminder, the `chat`,
`copy`, and `off` profiles, the `/grounded-copy:grounded` command, the governing
directive, and the preference file at `<config-dir>/grounded-copy/profile` are
Claude Code features. This adapter ships no hooks and writes no state.
`skills/grounded-copy/references/setup.md` documents that layer for readers who
also run Claude Code.

## License

MIT. The notice travels with this package in `LICENSE`.
"""

GENERATED = (
    (os.path.join(ADAPTER, ".codex-plugin", "plugin.json"), MANIFEST),
    (os.path.join(ADAPTER, "README.md"), README),
)


def _read(path):
    try:
        with open(path, "rb") as handle:
            return handle.read()
    except OSError:
        return None


def _write(path, payload):
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(payload)


def _payloads(root):
    """(destination, bytes) for every file the adapter carries."""
    items = []
    for source, destination in COPIES:
        payload = _read(os.path.join(root, source))
        if payload is None:
            raise IOError("unreadable source: " + source)
        items.append((destination, payload))
    for destination, text in GENERATED:
        items.append((destination, text.encode("utf-8")))
    return items


def build(root):
    for destination, payload in _payloads(root):
        _write(os.path.join(root, destination), payload)
        print("wrote " + destination.replace(os.sep, "/"))
    return EXIT_OK


def check(root):
    drift = []
    for destination, payload in _payloads(root):
        current = _read(os.path.join(root, destination))
        if current is None:
            drift.append("missing: " + destination.replace(os.sep, "/"))
        elif current != payload:
            drift.append("differs: " + destination.replace(os.sep, "/"))
    for line in drift:
        print("codex adapter " + line)
    if drift:
        print("run scripts/build_codex_adapter.py to rebuild")
        return EXIT_DRIFT
    print("codex adapter matches the canonical files")
    return EXIT_OK


def main(argv):
    root = REPO_ROOT
    if "--check" in argv:
        return check(root)
    return build(root)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
